# [셀프리뷰 프로젝트] 1. 코딩환경 설정 (Windows/Mac)

✔︎ 이번 프로젝트의 진행방식은 다음과 같습니다 :

- '셀프리뷰 프로젝트'는 코치의 리뷰를 거치지 않는 프로젝트입니다.
- 첨부된 파일에 안내된 절차에 따라 최소 5~10줄 이내의 간단한 코드를 작성함으로 스스로의 실력을 체크할 수 있습니다.
- 프로젝트 수행 결과 화면을 캡처 및 제출시, 담당코치가 훈련생 분의 학습현황을 파악하고 채점을 진행합니다.


✔︎ 프로젝트 수행에 어려움을 겪고 있다면?

- 만약 프로젝트 수행에 어려움을 겪고 있거나 제출을 끝냈다면, 코치 1:1 문의를 통해 예시 정답을 요청해 보세요.
- 웍스 내 자유게시판을 통해 다른 훈련생들과 문제점을 공유하고 해결방안을 도모하는 것도 좋은 방법입니다.

## 1. 가상환경 준비하기



In [ ]:
# 파이썬 프로그래밍을 하기 위한 런타임 환경을 구성합니다.
# 코드 편집기 또는 IDE를 통해 코드 작성을 준비합니다.

In [1]:
# sys 모듈을 통해 현재 파이썬 버전을 확인해보세요.
import sys
print(sys.version)

3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)]


## 2. 실행환경 점검하기

### [TODO] 1_ csv 파일 불러오기

In [3]:
# 주어진 csv 파일을 불러와 내용을 출력해보세요.
import pandas as pd

## 코드시작 ##

df = pd.read_csv('./zen of python.csv')

## 코드종료 ##
print(df)

                         Zen of Python, by Tim Peters  \
0                      Beautiful is better than ugly.   
1                   Explicit is better than implicit.   
2                      Simple is better than complex.   
3                 Complex is better than complicated.   
4                         Flat is better than nested.   
5                        Sparse is better than dense.   
6                                 Readability counts.   
7   Special cases aren't special enough to break t...   
8                 Although practicality beats purity.   
9                  Errors should never pass silently.   
10                        Unless explicitly silenced.   
11  In the face of ambiguity, refuse the temptatio...   
12  There should be one-- and preferably only one ...   
13  Although that way may not be obvious at first ...   
14                          Now is better than never.   
15     Although never is often better than right now.   
16  If the implementation is ha

### [TODO] 2_ 코드 구현하기

In [1]:
# 1. range() 함수를 사용해 1부터 n까지의 합을 구하는 함수를 만드세요.
# hint! for 문을 이용하여 작성합니다.

## 코드시작 ##
num = int(input()) #10
value = []
for i in range(1,num+1):
    value.append(i)
answer = sum(value)



## 코드종료 ##
print(answer)

55


In [47]:
# 2. 다음은 OO대학교 학생들의 수학 성적입니다. 성적의 평균을 구하세요.

scores = [85, 90, 100, 70, 65, 80, 75]
plus = 0
average = 0

## 코드시작 ##
for i in scores:
    plus += i
    
average = plus / len(scores)
## 코드종료 ##

print(average)

80.71428571428571


In [23]:
# 3. numpy 라이브러리를 활용하여 크기가 10인 랜덤 벡터를 만들고, 그 평균값을 구하세요.

import numpy as np
## 코드시작 ##
vector = np.random.random(10)
print(vector)

## 코드종료 ##
np.average(vector)

[0.03995921 0.42949218 0.31492687 0.63649114 0.34634715 0.04309736
 0.87991517 0.76324059 0.87809664 0.41750914]


0.4749075456542598

In [36]:
# 4. numpy 라이브러리를 활용하여 5X5 배열을 만들고, 첫번째 행과 두번째 행의 위치를 바꾸어보세요.

## 코드시작 ##

# 5x5 배열 생성
vector = np.array([np.arange(5),np.arange(5,10),np.arange(10,15),np.arange(15,20),np.arange(20,25)])

#임시 보관용 함수 생성
stay = np.array(vector[0])

#행 위치 변환
vector[0] = vector[1]
vector[1] = stay


## 코드종료 ##
print(vector)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [3]:
# 5. numpy 라이브러리를 활용해 다음 두 배열의 유클리드 거리를 구해보세요.
import numpy as np
a = np.array([1,2])
b = np.array([4,5])

## 코드시작 ##

distance = np.sqrt(sum((a-b)**2))

## 코드종료 ##

print("두 배열 사이의 거리 :", distance)

두 배열 사이의 거리 : 4.242640687119285


## 3. 셀프리뷰 진행하기

- 수행한 프로젝트 내용을 확인하고, 셀프리뷰를 진행합니다.
- 내가 작성한 코드에 오류는 없는지 또는 더 나은 방법은 없는지 고민해 봅니다.
- 리뷰를 완료했다면, 실행 결과 화면을 캡쳐 및 제출하여 수행여부를 증빙합니다. (파일첨부 NO! 본문에 이미지 삽입 YES!)
- 이번 차시에 궁금한 점이 있다면, 제출시 본문에 내용을 함께 작성하여 제출할 수 있습니다.

ALL RIGHTS RESERVED. ⓒNAVER Connect Foundation.